APP_PATH = "C:\\projects\\python\\data_quality"
APP_LOG_DIR = "@format {this.app_path}/logs"
APP_DATA_DIR = "@format {this.app_path}/data"
APP_SQL_DIR = "@format {this.app_path}/sql"

DATABASE_DW_HOST = "46.202.144.20"
DATABASE_DW_PORT = "2543"
DATABASE_DW_DB = "integration-dev"
DATABASE_DW_SCHEMA = "dw"

DATABASE_DEV_HOST = "46.202.144.20"
DATABASE_DEV_PORT = "2543"
DATABASE_DEV_DB = "integration-dev"
DATABASE_DEV_SCHEMA = "dw"